### ISSUE TITLE
Newbie experience

### ISSUE THREAD

**Issue by martinglass** [Aaronsss/RH-Setup#4]
Hi Aaron,

I've just across your RH-Setup repo and tried it out.

I ' M   V E R Y   I M P R E S S E D !

I wish I had come across it earlier. I'm testing RH out on the new RPi v5 board, and your RH-Setup script runs sooooo fast (partly because rebooting on RPi 5 is damn quick, compared to before). 

RH-Setup first stage completed in 2-4 minutes and second stage seemed to flash by, maybe a further 1 minute, 2 minutes max!

Here's my first time experience and feedback, in case it's any use.

1. I couldn't edit the firstrun.sh file using my Mac, due to user permissions. I chose the manual installation method (see 4. below)
 cd ~
 wget https://github.com/Aaronsss/RH-Setup/archive/refs/heads/main.zip
 unzip main.zip
 sudo chmod 744 ~/RH-Setup-main/rh-pi-setup.sh
 ~/RH-Setup-main/rh-pi-setup.sh

2. The first stage paused (when initiating raspi-config), and it asked the user to confirm Serial options (Login Shell = No, Serial Port Hardware Enabled = Yes, confirm = Enter).
A first time user wouldn't know the correct responses here, perhaps it's worth mentioning this in your README.md

3. The RH-Setup installation first stage completed ok, but at the end I got these messages and then the process failed to continue (see error log below)

To get round this, I manually created the folder  ("sudo mkdir /boot/RH") and re-ran the rh-pi-setup.sh script. The process continued and completed satisfactorily.

**ERROR LOG**
sh: 1: cannot create /boot/RH/RHInstalProgress.txt: Directory nonexistent
Sun 19 Nov 09:48:50 GMT 2023 RotorHazard first stage install completed in:  156 Seconds
Rebooting to complete install

Broadcast message from root@raspberrypi5 on pts/1 (Sun 2023-11-19 09:48:50 GMT):

The system will reboot now!

Connection to raspberrypi5.local closed by remote host.
Connection to raspberrypi5.local closed.

4. Running it manually, to initiate the 2nd Stage, after first reboot, I needed to manually re-enter the command "~/RH-Setup-main/rh-pi-setup.sh"

5. pi-fan-control.service failed to start up in systemctl
Running the script manually, the following log is returned:
Traceback (most recent call last):
  File "/home/martin/Raspberry-Pi-Fan-Control/run-fan.py", line 43, in <module>
    setup()
  File "/home/martin/Raspberry-Pi-Fan-Control/run-fan.py", line 13, in setup
    GPIO.setup(pin, GPIO.OUT)
RuntimeError: No access to /dev/mem.  Try running as root!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/martin/Raspberry-Pi-Fan-Control/run-fan.py", line 48, in <module>
    fan_on()
  File "/home/martin/Raspberry-Pi-Fan-Control/run-fan.py", line 25, in fan_on
    GPIO.output(pin, True)
RuntimeError: The GPIO channel has not been set up as an OUTPUT

6.  In pi-config-update.sh ...
      sudo -- bash -c 'echo "core_freq=250" >> /boot/config.txt' is not needed for Pi 4 and Pi 5.

7. rh-install.sh doesn't use the venv python virtual environment method.

**Comment by Aaronsss** [comment]
Thanks for the feedback @martinglass. Some responses below

1. Is there no way to change permissions on Mac? I don't have one to test with. I don't know of another good way to do a headless install without changing the firstrun.sh
2. This is a problem I will see if there is a work around as the intent is you shouldn't have to log into SSH or connect a monitor 
3. If installing via SD card you would have created an RH directory but I can add checks to create if needed.
4. Yep that is expected I will update the readme to say this
5. I wonder if that's a rpi5 thing. I don't have one to test with :( the fan control script could be replaced with the built in fan control. There is a work around to get it to turn fans on at a lower temp. Will look at adding it.
6. It is added under [pi3] flag so will only be used on pi3
7. I always find venvs a pain and this script is targeted at people who don't really want to do much ssh stuff meaning they are unlikely to run into issues with package dependencies from other installs. I may look at adding it in the future though

**Comment by martinglass** [comment]
Hope my feedback is useful. 

Although it's an admirable aim to provide  a fully headless install, I'm not convinced how important it is nowadays. The Pi OS installation App enables WiFi and login details for either SSH or Desktop easily. 

The real value of your RH-Setup, to me at least, is saving time and minimising/ eliminating user error.

**Comment by Aaronsss** [comment]
fixed via #5

implemented 2, 3, 4, 5, 7

I havent got a pi with fans on to test right now on the fan control but it should work fine. I would be intrested to know if it is fixed onthe pi5 I tested on a pi zero

**Comment by Aaronsss** [comment]
Closing as the issues appear resolved
